name: Test New CodeBuild Runner

on:
  workflow_dispatch:
  push:
    branches:
      - feature/runner-readme-update
    paths:
      - 'test-module/**'
      - 'terraform-aws-codebuild-github-runner/**'

permissions:
  contents: read
  id-token: write

jobs:
  test-runner:
    name: Test New Runner
    runs-on: codebuild-demo-runner-dev-runner-${github.run_id}-${github.run_attempt}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test AWS Credentials
        run: |
          echo "Testing AWS credentials..."
          aws sts get-caller-identity

      - name: Test Environment
        run: |
          echo "Testing runner environment..."
          echo "Runner: ${{ runner.name }}"
          echo "OS: ${{ runner.os }}"
          echo "Architecture: ${{ runner.arch }}"
          echo "Working Directory: $(pwd)"
          echo "User: $(whoami)"

      - name: Test Docker
        run: |
          echo "Testing Docker availability..."
          docker --version
          docker ps

      - name: Test AWS CLI
        run: |
          echo "AWS CLI Version:"
          aws --version
          echo ""
          echo "AWS Region:"
          echo $AWS_REGION
          echo ""
          echo "Caller Identity:"
          aws sts get-caller-identity --output json

      - name: Test Terraform
        run: |
          echo "Testing Terraform..."
          terraform version

      - name: Simple Build Test
        run: |
          echo "Running simple build test..."
          cd test-module
          echo "test" > test-file.txt
          cat test-file.txt

      - name: Summary
        if: always()
        run: |
          echo "## Test Runner Validation Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Runner:** \`${{ runner.name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** \`${{ github.run_id }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Run Attempt:** \`${{ github.run_attempt }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Capabilities Verified:" >> $GITHUB_STEP_SUMMARY
          echo "- AWS credentials via IAM role" >> $GITHUB_STEP_SUMMARY
          echo "- Docker support" >> $GITHUB_STEP_SUMMARY
          echo "- Terraform CLI" >> $GITHUB_STEP_SUMMARY
          echo "- Basic file operations" >> $GITHUB_STEP_SUMMARY
